### ISSUE TITLE
Cannot install plugin. It disappears after Flipper restart

### ISSUE THREAD

**Issue by ezhkov** [lbaldy/flipper-plugin-async-storage-advanced#2]
Flipper version: 0.113.0

![CleanShot 2021-10-04 at 10 19 15](https://user-images.githubusercontent.com/568355/135802974-b056c715-449a-4047-b6e4-5ab6ca0cd525.gif)

**Comment by lbaldy** [comment]
Thanks for reporting the issue. I was able to reproduce it. I will try to fix it over the weekend.

**Comment by lbaldy** [comment]
@ezhkov I released a new version 1.0.4 with the deps updated. If it still doesn't work, you can try going to settings -> 'reset all state' in Flipper. It helped me.  Please confirm, if it works I'll close this bug.

**Comment by ezhkov** [comment]
@lbaldy Thank you! Reset state was the thing! Now it all works perfect )
