### ISSUE TITLE
'Advanced Async Storage' is not supported

### ISSUE THREAD

**Issue by artstylee** [lbaldy/flipper-plugin-async-storage-advanced#3]
```
Plugin 'Advanced Async Storage' is unavailable
Plugin 'Advanced Async Storage' is not supported by the selected application 'motoNative' (Android).
```
![Без имени-1](https://user-images.githubusercontent.com/56781292/146634382-79806e83-f2d6-416f-ad73-f52ab2fe9ba9.jpg)

plugin doesnt work inside flipper client (win10)

**Comment by lbaldy** [comment]
Thanks for reporting the issue. Have you added the necessary configuration as well? Like import and include of the component?

**Comment by artstylee** [comment]
> Thanks for reporting the issue. Have you added the necessary configuration as well? Like import and include of the component?
i dont know rly it just started to work. maybe it was a flipper bug or smt..
